// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gameset.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventHookPhase int32

const (
	/// start gameset
	EventHookPhase_gameset_start EventHookPhase = 0
	/// -- turn lifecycle
	EventHookPhase_start_turn_phase EventHookPhase = 10
	/// ---- Draw phase (ddp)
	EventHookPhase_refill_action_card_phase EventHookPhase = 20
	EventHookPhase_refill_event_card_phase  EventHookPhase = 25
	/// ---- Move phase
	EventHookPhase_move_card_drop_phase         EventHookPhase = 30
	EventHookPhase_determine_move_phase         EventHookPhase = 40
	EventHookPhase_finish_move_phase            EventHookPhase = 50
	EventHookPhase_chara_change_phase           EventHookPhase = 60
	EventHookPhase_determine_chara_change_phase EventHookPhase = 70
	/// ---- Atk/Def Phase A
	EventHookPhase_attack_card_drop_phase_pA            EventHookPhase = 80
	EventHookPhase_defence_card_drop_phase_pA           EventHookPhase = 90
	EventHookPhase_determine_battle_point_phase_pA      EventHookPhase = 100
	EventHookPhase_battle_result_phase_pA               EventHookPhase = 110
	EventHookPhase_damage_phase_pA                      EventHookPhase = 120
	EventHookPhase_dead_chara_change_phase_pA           EventHookPhase = 125
	EventHookPhase_determine_dead_chara_change_phase_pA EventHookPhase = 130
	/// ---- Atk/Def Phase B
	EventHookPhase_attack_card_drop_phase_pB            EventHookPhase = 140
	EventHookPhase_defence_card_drop_phase_pB           EventHookPhase = 150
	EventHookPhase_determine_battle_point_phase_pB      EventHookPhase = 160
	EventHookPhase_battle_result_phase_pB               EventHookPhase = 170
	EventHookPhase_damage_phase_pB                      EventHookPhase = 180
	EventHookPhase_determine_dead_chara_change_phase_pB EventHookPhase = 190
	/// ------ change char when the charecter dead
	EventHookPhase_dead_chara_change_phase_pB        EventHookPhase = 200
	EventHookPhase_determine_dead_chara_change_phase EventHookPhase = 210
	/// -- endof turn lifecycle
	EventHookPhase_finish_turn_phase EventHookPhase = 220
	/// endof game set
	EventHookPhase_gameset_end EventHookPhase = 230
)

var EventHookPhase_name = map[int32]string{
	0:   "gameset_start",
	10:  "start_turn_phase",
	20:  "refill_action_card_phase",
	25:  "refill_event_card_phase",
	30:  "move_card_drop_phase",
	40:  "determine_move_phase",
	50:  "finish_move_phase",
	60:  "chara_change_phase",
	70:  "determine_chara_change_phase",
	80:  "attack_card_drop_phase_pA",
	90:  "defence_card_drop_phase_pA",
	100: "determine_battle_point_phase_pA",
	110: "battle_result_phase_pA",
	120: "damage_phase_pA",
	125: "dead_chara_change_phase_pA",
	130: "determine_dead_chara_change_phase_pA",
	140: "attack_card_drop_phase_pB",
	150: "defence_card_drop_phase_pB",
	160: "determine_battle_point_phase_pB",
	170: "battle_result_phase_pB",
	180: "damage_phase_pB",
	190: "determine_dead_chara_change_phase_pB",
	200: "dead_chara_change_phase_pB",
	210: "determine_dead_chara_change_phase",
	220: "finish_turn_phase",
	230: "gameset_end",
}

var EventHookPhase_value = map[string]int32{
	"gameset_start":                        0,
	"start_turn_phase":                     10,
	"refill_action_card_phase":             20,
	"refill_event_card_phase":              25,
	"move_card_drop_phase":                 30,
	"determine_move_phase":                 40,
	"finish_move_phase":                    50,
	"chara_change_phase":                   60,
	"determine_chara_change_phase":         70,
	"attack_card_drop_phase_pA":            80,
	"defence_card_drop_phase_pA":           90,
	"determine_battle_point_phase_pA":      100,
	"battle_result_phase_pA":               110,
	"damage_phase_pA":                      120,
	"dead_chara_change_phase_pA":           125,
	"determine_dead_chara_change_phase_pA": 130,
	"attack_card_drop_phase_pB":            140,
	"defence_card_drop_phase_pB":           150,
	"determine_battle_point_phase_pB":      160,
	"battle_result_phase_pB":               170,
	"damage_phase_pB":                      180,
	"determine_dead_chara_change_phase_pB": 190,
	"dead_chara_change_phase_pB":           200,
	"determine_dead_chara_change_phase":    210,
	"finish_turn_phase":                    220,
	"gameset_end":                          230,
}

func (x EventHookPhase) String() string {
	return proto.EnumName(EventHookPhase_name, int32(x))
}

func (EventHookPhase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{0}
}

type EventHookType int32

const (
	EventHookType_Instant EventHookType = 0
	EventHookType_Before  EventHookType = 1
	EventHookType_After   EventHookType = 2
	EventHookType_Proxy   EventHookType = 3
)

var EventHookType_name = map[int32]string{
	0: "Instant",
	1: "Before",
	2: "After",
	3: "Proxy",
}

var EventHookType_value = map[string]int32{
	"Instant": 0,
	"Before":  1,
	"After":   2,
	"Proxy":   3,
}

func (x EventHookType) String() string {
	return proto.EnumName(EventHookType_name, int32(x))
}

func (EventHookType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{1}
}

type ACType int32

const (
	ACType_ATK  ACType = 0
	ACType_DEF  ACType = 1
	ACType_MOV  ACType = 2
	ACType_STR  ACType = 3
	ACType_GUN  ACType = 4
	ACType_NULL ACType = 5
)

var ACType_name = map[int32]string{
	0: "ATK",
	1: "DEF",
	2: "MOV",
	3: "STR",
	4: "GUN",
	5: "NULL",
}

var ACType_value = map[string]int32{
	"ATK":  0,
	"DEF":  1,
	"MOV":  2,
	"STR":  3,
	"GUN":  4,
	"NULL": 5,
}

func (x ACType) String() string {
	return proto.EnumName(ACType_name, int32(x))
}

func (ACType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{2}
}

type ActionCard struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpType               ACType   `protobuf:"varint,2,opt,name=UpType,proto3,enum=ULZProto.ACType" json:"UpType,omitempty"`
	UpValue              int32    `protobuf:"zigzag32,3,opt,name=UpValue,proto3" json:"UpValue,omitempty"`
	DwType               ACType   `protobuf:"varint,4,opt,name=DwType,proto3,enum=ULZProto.ACType" json:"DwType,omitempty"`
	DwValue              int32    `protobuf:"zigzag32,5,opt,name=DwValue,proto3" json:"DwValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionCard) Reset()         { *m = ActionCard{} }
func (m *ActionCard) String() string { return proto.CompactTextString(m) }
func (*ActionCard) ProtoMessage()    {}
func (*ActionCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{0}
}

func (m *ActionCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionCard.Unmarshal(m, b)
}
func (m *ActionCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionCard.Marshal(b, m, deterministic)
}
func (m *ActionCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionCard.Merge(m, src)
}
func (m *ActionCard) XXX_Size() int {
	return xxx_messageInfo_ActionCard.Size(m)
}
func (m *ActionCard) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionCard.DiscardUnknown(m)
}

var xxx_messageInfo_ActionCard proto.InternalMessageInfo

func (m *ActionCard) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ActionCard) GetUpType() ACType {
	if m != nil {
		return m.UpType
	}
	return ACType_ATK
}

func (m *ActionCard) GetUpValue() int32 {
	if m != nil {
		return m.UpValue
	}
	return 0
}

func (m *ActionCard) GetDwType() ACType {
	if m != nil {
		return m.DwType
	}
	return ACType_ATK
}

func (m *ActionCard) GetDwValue() int32 {
	if m != nil {
		return m.DwValue
	}
	return 0
}

type Status struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Desription           string         `protobuf:"bytes,3,opt,name=Desription,proto3" json:"Desription,omitempty"`
	Weight               int32          `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Count                int32          `protobuf:"varint,5,opt,name=Count,proto3" json:"Count,omitempty"`
	TriggerFunc          []byte         `protobuf:"bytes,6,opt,name=TriggerFunc,proto3" json:"TriggerFunc,omitempty"`
	EHPhase              EventHookPhase `protobuf:"varint,7,opt,name=EHPhase,proto3,enum=ULZProto.EventHookPhase" json:"EHPhase,omitempty"`
	EHType               EventHookType  `protobuf:"varint,8,opt,name=EHType,proto3,enum=ULZProto.EventHookType" json:"EHType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Status) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Status) GetDesription() string {
	if m != nil {
		return m.Desription
	}
	return ""
}

func (m *Status) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Status) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Status) GetTriggerFunc() []byte {
	if m != nil {
		return m.TriggerFunc
	}
	return nil
}

func (m *Status) GetEHPhase() EventHookPhase {
	if m != nil {
		return m.EHPhase
	}
	return EventHookPhase_gameset_start
}

func (m *Status) GetEHType() EventHookType {
	if m != nil {
		return m.EHType
	}
	return EventHookType_Instant
}

type CardCharInt struct {
	CcId                 string    `protobuf:"bytes,1,opt,name=CcId,proto3" json:"CcId,omitempty"`
	Hp                   int32     `protobuf:"zigzag32,2,opt,name=Hp,proto3" json:"Hp,omitempty"`
	HpInt                int32     `protobuf:"zigzag32,3,opt,name=HpInt,proto3" json:"HpInt,omitempty"`
	Atk                  int32     `protobuf:"zigzag32,4,opt,name=Atk,proto3" json:"Atk,omitempty"`
	AtkInt               int32     `protobuf:"zigzag32,5,opt,name=AtkInt,proto3" json:"AtkInt,omitempty"`
	Def                  int32     `protobuf:"zigzag32,6,opt,name=Def,proto3" json:"Def,omitempty"`
	DefInt               int32     `protobuf:"zigzag32,7,opt,name=DefInt,proto3" json:"DefInt,omitempty"`
	StatusInt            []*Status `protobuf:"bytes,8,rep,name=StatusInt,proto3" json:"StatusInt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CardCharInt) Reset()         { *m = CardCharInt{} }
func (m *CardCharInt) String() string { return proto.CompactTextString(m) }
func (*CardCharInt) ProtoMessage()    {}
func (*CardCharInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{2}
}

func (m *CardCharInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardCharInt.Unmarshal(m, b)
}
func (m *CardCharInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardCharInt.Marshal(b, m, deterministic)
}
func (m *CardCharInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardCharInt.Merge(m, src)
}
func (m *CardCharInt) XXX_Size() int {
	return xxx_messageInfo_CardCharInt.Size(m)
}
func (m *CardCharInt) XXX_DiscardUnknown() {
	xxx_messageInfo_CardCharInt.DiscardUnknown(m)
}

var xxx_messageInfo_CardCharInt proto.InternalMessageInfo

func (m *CardCharInt) GetCcId() string {
	if m != nil {
		return m.CcId
	}
	return ""
}

func (m *CardCharInt) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *CardCharInt) GetHpInt() int32 {
	if m != nil {
		return m.HpInt
	}
	return 0
}

func (m *CardCharInt) GetAtk() int32 {
	if m != nil {
		return m.Atk
	}
	return 0
}

func (m *CardCharInt) GetAtkInt() int32 {
	if m != nil {
		return m.AtkInt
	}
	return 0
}

func (m *CardCharInt) GetDef() int32 {
	if m != nil {
		return m.Def
	}
	return 0
}

func (m *CardCharInt) GetDefInt() int32 {
	if m != nil {
		return m.DefInt
	}
	return 0
}

func (m *CardCharInt) GetStatusInt() []*Status {
	if m != nil {
		return m.StatusInt
	}
	return nil
}

type Player struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CCSet                []*CardCharInt `protobuf:"bytes,2,rep,name=CCSet,proto3" json:"CCSet,omitempty"`
	Deck                 []*ActionCard  `protobuf:"bytes,3,rep,name=Deck,proto3" json:"Deck,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetCCSet() []*CardCharInt {
	if m != nil {
		return m.CCSet
	}
	return nil
}

func (m *Player) GetDeck() []*ActionCard {
	if m != nil {
		return m.Deck
	}
	return nil
}

type Log struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	LogLevel             int32    `protobuf:"varint,2,opt,name=LogLevel,proto3" json:"LogLevel,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{4}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Log) GetLogLevel() int32 {
	if m != nil {
		return m.LogLevel
	}
	return 0
}

func (m *Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Room struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host                 *Player        `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Dueler               *Player        `protobuf:"bytes,3,opt,name=Dueler,proto3" json:"Dueler,omitempty"`
	Turns                uint32         `protobuf:"varint,4,opt,name=Turns,proto3" json:"Turns,omitempty"`
	Logger               *Log           `protobuf:"bytes,5,opt,name=logger,proto3" json:"logger,omitempty"`
	EventCounter         int32          `protobuf:"zigzag32,6,opt,name=EventCounter,proto3" json:"EventCounter,omitempty"`
	EventPhase           EventHookPhase `protobuf:"varint,7,opt,name=EventPhase,proto3,enum=ULZProto.EventHookPhase" json:"EventPhase,omitempty"`
	FirstPlayer          string         `protobuf:"bytes,8,opt,name=FirstPlayer,proto3" json:"FirstPlayer,omitempty"`
	SecPlayer            string         `protobuf:"bytes,9,opt,name=SecPlayer,proto3" json:"SecPlayer,omitempty"`
	Winner               string         `protobuf:"bytes,10,opt,name=Winner,proto3" json:"Winner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{5}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetHost() *Player {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *Room) GetDueler() *Player {
	if m != nil {
		return m.Dueler
	}
	return nil
}

func (m *Room) GetTurns() uint32 {
	if m != nil {
		return m.Turns
	}
	return 0
}

func (m *Room) GetLogger() *Log {
	if m != nil {
		return m.Logger
	}
	return nil
}

func (m *Room) GetEventCounter() int32 {
	if m != nil {
		return m.EventCounter
	}
	return 0
}

func (m *Room) GetEventPhase() EventHookPhase {
	if m != nil {
		return m.EventPhase
	}
	return EventHookPhase_gameset_start
}

func (m *Room) GetFirstPlayer() string {
	if m != nil {
		return m.FirstPlayer
	}
	return ""
}

func (m *Room) GetSecPlayer() string {
	if m != nil {
		return m.SecPlayer
	}
	return ""
}

func (m *Room) GetWinner() string {
	if m != nil {
		return m.Winner
	}
	return ""
}

type DiceResult struct {
	ATK                  int32    `protobuf:"zigzag32,1,opt,name=ATK,proto3" json:"ATK,omitempty"`
	DEF                  int32    `protobuf:"zigzag32,2,opt,name=DEF,proto3" json:"DEF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiceResult) Reset()         { *m = DiceResult{} }
func (m *DiceResult) String() string { return proto.CompactTextString(m) }
func (*DiceResult) ProtoMessage()    {}
func (*DiceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{6}
}

func (m *DiceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiceResult.Unmarshal(m, b)
}
func (m *DiceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiceResult.Marshal(b, m, deterministic)
}
func (m *DiceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiceResult.Merge(m, src)
}
func (m *DiceResult) XXX_Size() int {
	return xxx_messageInfo_DiceResult.Size(m)
}
func (m *DiceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DiceResult.DiscardUnknown(m)
}

var xxx_messageInfo_DiceResult proto.InternalMessageInfo

func (m *DiceResult) GetATK() int32 {
	if m != nil {
		return m.ATK
	}
	return 0
}

func (m *DiceResult) GetDEF() int32 {
	if m != nil {
		return m.DEF
	}
	return 0
}

type GameSet struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Self                 *Player       `protobuf:"bytes,2,opt,name=Self,proto3" json:"Self,omitempty"`
	Opposite             *Player       `protobuf:"bytes,3,opt,name=Opposite,proto3" json:"Opposite,omitempty"`
	EventCounter         int32         `protobuf:"zigzag32,4,opt,name=EventCounter,proto3" json:"EventCounter,omitempty"`
	Turns                int32         `protobuf:"zigzag32,5,opt,name=Turns,proto3" json:"Turns,omitempty"`
	ATKDice              int32         `protobuf:"zigzag32,6,opt,name=ATKDice,proto3" json:"ATKDice,omitempty"`
	DEFDice              int32         `protobuf:"zigzag32,7,opt,name=DEFDice,proto3" json:"DEFDice,omitempty"`
	RollResult           []*DiceResult `protobuf:"bytes,8,rep,name=RollResult,proto3" json:"RollResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameSet) Reset()         { *m = GameSet{} }
func (m *GameSet) String() string { return proto.CompactTextString(m) }
func (*GameSet) ProtoMessage()    {}
func (*GameSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{7}
}

func (m *GameSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSet.Unmarshal(m, b)
}
func (m *GameSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSet.Marshal(b, m, deterministic)
}
func (m *GameSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSet.Merge(m, src)
}
func (m *GameSet) XXX_Size() int {
	return xxx_messageInfo_GameSet.Size(m)
}
func (m *GameSet) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSet.DiscardUnknown(m)
}

var xxx_messageInfo_GameSet proto.InternalMessageInfo

func (m *GameSet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GameSet) GetSelf() *Player {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *GameSet) GetOpposite() *Player {
	if m != nil {
		return m.Opposite
	}
	return nil
}

func (m *GameSet) GetEventCounter() int32 {
	if m != nil {
		return m.EventCounter
	}
	return 0
}

func (m *GameSet) GetTurns() int32 {
	if m != nil {
		return m.Turns
	}
	return 0
}

func (m *GameSet) GetATKDice() int32 {
	if m != nil {
		return m.ATKDice
	}
	return 0
}

func (m *GameSet) GetDEFDice() int32 {
	if m != nil {
		return m.DEFDice
	}
	return 0
}

func (m *GameSet) GetRollResult() []*DiceResult {
	if m != nil {
		return m.RollResult
	}
	return nil
}

type PlayerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d98f4532e8e3906a, []int{8}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterEnum("ULZProto.EventHookPhase", EventHookPhase_name, EventHookPhase_value)
	proto.RegisterEnum("ULZProto.EventHookType", EventHookType_name, EventHookType_value)
	proto.RegisterEnum("ULZProto.ACType", ACType_name, ACType_value)
	proto.RegisterType((*ActionCard)(nil), "ULZProto.ActionCard")
	proto.RegisterType((*Status)(nil), "ULZProto.Status")
	proto.RegisterType((*CardCharInt)(nil), "ULZProto.CardCharInt")
	proto.RegisterType((*Player)(nil), "ULZProto.Player")
	proto.RegisterType((*Log)(nil), "ULZProto.Log")
	proto.RegisterType((*Room)(nil), "ULZProto.Room")
	proto.RegisterType((*DiceResult)(nil), "ULZProto.DiceResult")
	proto.RegisterType((*GameSet)(nil), "ULZProto.GameSet")
	proto.RegisterType((*PlayerInfo)(nil), "ULZProto.PlayerInfo")
}

func init() { proto.RegisterFile("proto/gameset.proto", fileDescriptor_d98f4532e8e3906a) }

var fileDescriptor_d98f4532e8e3906a = []byte{
	// 1131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xbd, 0x73, 0x1b, 0x45,
	0x14, 0xcf, 0xe9, 0x5b, 0x4f, 0xb1, 0x59, 0xbd, 0x28, 0xce, 0xc5, 0x31, 0x8e, 0x10, 0x86, 0x11,
	0x86, 0x71, 0x18, 0x43, 0x41, 0xc1, 0xc0, 0xe8, 0x33, 0xd2, 0x58, 0x71, 0x3c, 0x6b, 0x39, 0x0c,
	0x69, 0x34, 0x1b, 0x69, 0x25, 0xdd, 0xf8, 0x74, 0x77, 0x73, 0xb7, 0x72, 0xe2, 0x82, 0x02, 0x6a,
	0x9a, 0x34, 0xd4, 0x14, 0x54, 0xd4, 0xd4, 0xd4, 0xcc, 0xd0, 0xd1, 0x31, 0x43, 0xcd, 0xdf, 0x91,
	0xd9, 0xdd, 0x93, 0xee, 0x1c, 0x4b, 0x49, 0xba, 0xf7, 0xde, 0xef, 0x77, 0x6f, 0xdf, 0xc7, 0x6f,
	0x57, 0x82, 0x5b, 0x9e, 0xef, 0x0a, 0xf7, 0xc1, 0x84, 0xcd, 0x78, 0xc0, 0xc5, 0x81, 0xf2, 0x30,
	0x77, 0xd6, 0x7b, 0x7a, 0x22, 0xad, 0xca, 0x6f, 0x06, 0x40, 0x6d, 0x28, 0x2c, 0xd7, 0x69, 0x30,
	0x7f, 0x84, 0x9b, 0x90, 0xb0, 0x46, 0xa6, 0x51, 0x36, 0xaa, 0x79, 0x9a, 0xb0, 0x46, 0x58, 0x85,
	0xcc, 0x99, 0xd7, 0xbf, 0xf4, 0xb8, 0x99, 0x28, 0x1b, 0xd5, 0xcd, 0x43, 0x72, 0xb0, 0xf8, 0xf2,
	0xa0, 0xd6, 0x90, 0x71, 0x1a, 0xe2, 0x68, 0x42, 0xf6, 0xcc, 0x7b, 0xc2, 0xec, 0x39, 0x37, 0x93,
	0x65, 0xa3, 0x5a, 0xa4, 0x0b, 0x57, 0xe6, 0x68, 0x3e, 0x57, 0x39, 0x52, 0xeb, 0x72, 0x68, 0x5c,
	0xe6, 0x68, 0x3e, 0xd7, 0x39, 0xd2, 0x3a, 0x47, 0xe8, 0x56, 0x7e, 0x4c, 0x40, 0xe6, 0x54, 0x30,
	0x31, 0x0f, 0xae, 0x95, 0x88, 0x90, 0x3a, 0x66, 0x33, 0x5d, 0x60, 0x9e, 0x2a, 0x1b, 0x77, 0x01,
	0x9a, 0x3c, 0xf0, 0x2d, 0x4f, 0x36, 0xa6, 0xea, 0xc9, 0xd3, 0x58, 0x04, 0xb7, 0x20, 0xf3, 0x1d,
	0xb7, 0x26, 0x53, 0xa1, 0x4a, 0x4a, 0xd3, 0xd0, 0xc3, 0x12, 0xa4, 0x1b, 0xee, 0xdc, 0x11, 0xea,
	0xf8, 0x34, 0xd5, 0x0e, 0x96, 0xa1, 0xd0, 0xf7, 0xad, 0xc9, 0x84, 0xfb, 0xed, 0xb9, 0x33, 0x34,
	0x33, 0x65, 0xa3, 0x7a, 0x93, 0xc6, 0x43, 0x78, 0x08, 0xd9, 0x56, 0xe7, 0x64, 0xca, 0x02, 0x6e,
	0x66, 0x55, 0x8f, 0x66, 0xd4, 0x63, 0xeb, 0x82, 0x3b, 0xa2, 0xe3, 0xba, 0xe7, 0x0a, 0xa7, 0x0b,
	0x22, 0x3e, 0x80, 0x4c, 0xab, 0xa3, 0xc6, 0x92, 0x53, 0x9f, 0xdc, 0x59, 0xf1, 0x89, 0x9e, 0x8e,
	0xa6, 0x55, 0xfe, 0x36, 0xa0, 0x20, 0x97, 0xd4, 0x98, 0x32, 0xbf, 0xeb, 0x08, 0xd9, 0x78, 0x63,
	0xd8, 0x5d, 0x8c, 0x42, 0xd9, 0x72, 0x38, 0x1d, 0x4f, 0x8d, 0xa2, 0x48, 0x13, 0x1d, 0x4f, 0x36,
	0xd4, 0xf1, 0xba, 0x8e, 0x08, 0x77, 0xa2, 0x1d, 0x24, 0x90, 0xac, 0x89, 0x73, 0xd5, 0x7b, 0x91,
	0x4a, 0x53, 0x0e, 0xa4, 0x26, 0xce, 0xbb, 0x61, 0xe7, 0x45, 0x1a, 0x7a, 0x92, 0xd9, 0xe4, 0x63,
	0xd5, 0x72, 0x91, 0x4a, 0x53, 0x32, 0x9b, 0x7c, 0x2c, 0x99, 0x59, 0xcd, 0xd4, 0x1e, 0x1e, 0x40,
	0x5e, 0x2f, 0x48, 0x42, 0xb9, 0x72, 0xb2, 0x5a, 0x88, 0x2f, 0x5a, 0x43, 0x34, 0xa2, 0x54, 0x5c,
	0xc8, 0x9c, 0xd8, 0xec, 0x92, 0xfb, 0xd7, 0x16, 0xfa, 0x29, 0xa4, 0x1b, 0x8d, 0x53, 0x2e, 0xcc,
	0x84, 0xca, 0x72, 0x3b, 0xca, 0x12, 0xeb, 0x9e, 0x6a, 0x0e, 0x56, 0x21, 0xd5, 0xe4, 0xc3, 0x73,
	0x33, 0xa9, 0xb8, 0xa5, 0x98, 0xb4, 0x96, 0xa2, 0xa6, 0x8a, 0x51, 0xf9, 0x1e, 0x92, 0x3d, 0x77,
	0x82, 0x3b, 0x90, 0xef, 0x5b, 0x33, 0x1e, 0x08, 0x36, 0xf3, 0xd4, 0xa1, 0x49, 0x1a, 0x05, 0x70,
	0x1b, 0x72, 0x3d, 0x77, 0xd2, 0xe3, 0x17, 0xdc, 0x56, 0x53, 0x4c, 0xd3, 0xa5, 0x2f, 0xd5, 0xf9,
	0x88, 0x07, 0x01, 0x9b, 0xf0, 0x50, 0x51, 0x0b, 0xb7, 0xf2, 0x6f, 0x02, 0x52, 0xd4, 0x75, 0x67,
	0xd7, 0x5a, 0xd9, 0x83, 0x54, 0xc7, 0x0d, 0x84, 0x4a, 0x75, 0x65, 0x1e, 0xba, 0x75, 0xaa, 0x50,
	0x75, 0x41, 0xe6, 0xdc, 0xe6, 0xbe, 0xca, 0xbb, 0x8a, 0x17, 0xe2, 0x72, 0x9d, 0xfd, 0xb9, 0xef,
	0x04, 0x6a, 0x75, 0x1b, 0x54, 0x3b, 0xf8, 0x11, 0x64, 0x6c, 0x57, 0x6a, 0x51, 0x2d, 0xaf, 0x70,
	0xb8, 0x11, 0x7d, 0xdf, 0x73, 0x27, 0x34, 0x04, 0xb1, 0x02, 0x37, 0x95, 0xb0, 0x94, 0xa8, 0xb9,
	0x1f, 0x2e, 0xf5, 0x4a, 0x0c, 0xbf, 0x02, 0x50, 0xfe, 0xbb, 0x69, 0x39, 0xc6, 0x95, 0x97, 0xa4,
	0x6d, 0xf9, 0x81, 0xd0, 0x15, 0x2b, 0x4d, 0xe7, 0x69, 0x3c, 0x24, 0x27, 0x7f, 0xca, 0x87, 0x21,
	0x9e, 0x57, 0x78, 0x14, 0x50, 0x57, 0xd2, 0x72, 0x1c, 0xee, 0x9b, 0xa0, 0xa0, 0xd0, 0xab, 0x7c,
	0x0e, 0xd0, 0xb4, 0x86, 0x9c, 0xf2, 0x60, 0x6e, 0x6b, 0xe5, 0xf6, 0x8f, 0xd4, 0x84, 0xa5, 0x72,
	0xfb, 0x47, 0x4a, 0xa1, 0xad, 0x76, 0x28, 0x79, 0x69, 0x56, 0x5e, 0x26, 0x20, 0xfb, 0x90, 0xcd,
	0xb8, 0x94, 0xc7, 0x8a, 0x85, 0x9c, 0x72, 0x7b, 0xbc, 0x7e, 0x21, 0x12, 0xc5, 0xcf, 0x20, 0xf7,
	0xd8, 0xf3, 0xdc, 0xc0, 0x12, 0x7c, 0xed, 0x4a, 0x96, 0x8c, 0x6b, 0x73, 0x4d, 0xad, 0x98, 0xeb,
	0x72, 0x71, 0xfa, 0x7a, 0x85, 0x8b, 0x33, 0x21, 0x5b, 0xeb, 0x1f, 0xc9, 0xf6, 0xc2, 0x65, 0x2c,
	0x5c, 0xf5, 0x12, 0xb6, 0xda, 0x0a, 0xc9, 0x86, 0x2f, 0xa1, 0x76, 0xf1, 0x4b, 0x00, 0xea, 0xda,
	0xb6, 0x9e, 0x47, 0x78, 0xd1, 0x62, 0xb2, 0x8f, 0x66, 0x45, 0x63, 0xbc, 0x4a, 0x1b, 0x40, 0xd7,
	0xdd, 0x75, 0xc6, 0xae, 0x9c, 0xca, 0xf2, 0xdd, 0x48, 0x74, 0x57, 0x3f, 0xa1, 0xb2, 0x62, 0x4b,
	0xd8, 0x0b, 0xad, 0x6b, 0x67, 0xff, 0x65, 0x06, 0x36, 0xaf, 0x8a, 0x00, 0x8b, 0xb0, 0x11, 0xfe,
	0xb8, 0x0c, 0x02, 0xc1, 0x7c, 0x41, 0x6e, 0x60, 0x09, 0x88, 0x32, 0x07, 0x62, 0xee, 0x3b, 0x03,
	0x4f, 0xd2, 0x08, 0xe0, 0x0e, 0x98, 0x3e, 0x1f, 0x5b, 0xb6, 0x3d, 0x60, 0xea, 0x6e, 0x0e, 0x86,
	0xcc, 0x1f, 0x85, 0x68, 0x09, 0xef, 0xc1, 0x9d, 0x10, 0xe5, 0x32, 0x7f, 0x1c, 0xbc, 0x8b, 0x26,
	0x94, 0x66, 0xee, 0x05, 0xd7, 0xc1, 0x91, 0xef, 0x7a, 0x21, 0xb2, 0x2b, 0x91, 0x11, 0x17, 0xdc,
	0x9f, 0x59, 0x0e, 0x1f, 0x28, 0x8e, 0x46, 0xaa, 0x78, 0x1b, 0x8a, 0x63, 0xcb, 0xb1, 0x82, 0x69,
	0x3c, 0x7c, 0x88, 0x5b, 0x80, 0xc3, 0x29, 0xf3, 0xd9, 0x60, 0x38, 0x65, 0xce, 0x64, 0x11, 0xff,
	0x1a, 0xcb, 0xb0, 0x13, 0x25, 0x5a, 0xc1, 0x68, 0xe3, 0xfb, 0x70, 0x97, 0x09, 0xc1, 0x86, 0xe7,
	0xaf, 0x97, 0x31, 0xf0, 0x6a, 0xe4, 0x04, 0x77, 0x61, 0x7b, 0xc4, 0xc7, 0xdc, 0x19, 0xf2, 0x55,
	0xf8, 0x53, 0xfc, 0x10, 0xee, 0x47, 0x07, 0x3c, 0x63, 0x42, 0xd8, 0x7c, 0xe0, 0xb9, 0x96, 0x23,
	0x22, 0xd2, 0x08, 0xb7, 0x61, 0x2b, 0x84, 0x7c, 0xb5, 0xb8, 0x08, 0x73, 0xf0, 0x16, 0xbc, 0x37,
	0x62, 0x33, 0xb6, 0xa8, 0x48, 0x06, 0x5f, 0xe8, 0x53, 0xd9, 0x68, 0x45, 0xc5, 0x12, 0xff, 0x01,
	0x3f, 0x81, 0xbd, 0xe8, 0xd4, 0x37, 0x30, 0x7f, 0x32, 0x70, 0x77, 0x7d, 0x7f, 0x75, 0xf2, 0xb3,
	0x81, 0xf7, 0xdf, 0xd0, 0x60, 0x9d, 0xfc, 0x62, 0xe0, 0xde, 0xdb, 0x3a, 0xac, 0x93, 0x5f, 0x0d,
	0xbc, 0xb7, 0xa6, 0xc5, 0x3a, 0xf9, 0xdd, 0xc0, 0xd2, 0xeb, 0x3d, 0xd6, 0xc9, 0x1f, 0xc6, 0x3b,
	0x36, 0x51, 0x27, 0x7f, 0x86, 0x45, 0xae, 0x25, 0xfc, 0x65, 0xe0, 0xc7, 0xf0, 0xc1, 0x5b, 0x73,
	0x91, 0x7f, 0x0c, 0xdc, 0x5a, 0xca, 0x27, 0x26, 0xe2, 0xff, 0x0c, 0x24, 0x50, 0x58, 0xc8, 0x9d,
	0x3b, 0x23, 0xf2, 0xbf, 0xb1, 0xff, 0x0d, 0x6c, 0x5c, 0xf9, 0xc1, 0xc6, 0x02, 0x64, 0xbb, 0x4e,
	0x20, 0x98, 0x23, 0xef, 0x02, 0x40, 0xa6, 0xce, 0xc7, 0xae, 0xcf, 0x89, 0x81, 0x79, 0x48, 0xd7,
	0xc6, 0x82, 0xfb, 0x24, 0x21, 0xcd, 0x13, 0xdf, 0x7d, 0x71, 0x49, 0x92, 0xfb, 0xdf, 0x42, 0x46,
	0xff, 0x0f, 0xc2, 0xac, 0x7a, 0xdd, 0xc8, 0x0d, 0x69, 0x34, 0x5b, 0x6d, 0x62, 0x48, 0xe3, 0xd1,
	0xe3, 0x27, 0x24, 0x21, 0x8d, 0xd3, 0x3e, 0x25, 0x49, 0x69, 0x3c, 0x3c, 0x3b, 0x26, 0x29, 0xcc,
	0x41, 0xea, 0xf8, 0xac, 0xd7, 0x23, 0xe9, 0x67, 0x19, 0xf5, 0xa7, 0xee, 0x8b, 0x57, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc0, 0x5c, 0x1a, 0x54, 0xeb, 0x09, 0x00, 0x00,
}
